### ISSUE TITLE
`unknown encoding: idna` from report submission

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip#118]
At the end of a trace:
```
Traceback (most recent call last):
  File "/usr/bin/reprozip", line 9, in <module>
    load_entry_point('reprozip==0.6.2', 'console_scripts', 'reprozip')()
  File "/usr/lib64/python2.7/site-packages/reprozip/main.py", line 328, in main
    submit_usage_report(result=type(e).__name__)
  File "/usr/lib64/python2.7/site-packages/reprozip/common.py", line 390, in submit_usage_report
    usagestats.PYTHON_VERSION)
  File "/usr/lib/python2.7/site-packages/usagestats.py", line 260, in submit
    timeout=1, verify=self.ssl_verify)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 422, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 360, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 294, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 352, in prepare_url
    host = host.encode('idna').decode('utf-8')
LookupError: unknown encoding: idna
```
requests is 2.3.0, on Fedora 21.

**Comment by remram44** [comment]
At the very least, might want to catch and ignore errors from submit_usage_report(), though this looks like a serious bug on requests' part.

**Comment by remram44** [comment]
`u'test'.encode('idna')` works fine on the same machine if run directly in the interactive interpreter. What is going on?
