### ISSUE TITLE
ValueError when tracing website

### ISSUE THREAD

**Issue by VickySteeves** [ViDA-NYU/reprozip#200]
Hi all (specifically @remram44),

I was trying to pack up my website build on the Nikola static site generator as a new way to make archival backups, and got this really weird error: 
````
(venv) vicky@steevesv:~/Downloads/Nikola-Site$ reprozip trace nikola build
Scanning posts......done!
[REPROZIP] 14:32:02.564 WARNING: Some files were read and then written. We will only pack the final version of the file; reproducible experiments shouldn't change their input files
Traceback (most recent call last):
  File "/home/vicky/.local/bin/reprozip", line 11, in <module>
    sys.exit(main())
  File "/home/vicky/.local/lib/python2.7/site-packages/reprozip/main.py", line 364, in main
    args.func(args)
  File "/home/vicky/.local/lib/python2.7/site-packages/reprozip/main.py", line 188, in trace
    overwrite=False)
  File "/home/vicky/.local/lib/python2.7/site-packages/reprozip/tracer/trace.py", line 283, in write_configuration
    files, packages = identify_packages(files)
  File "/home/vicky/.local/lib/python2.7/site-packages/reprozip/tracer/linux_pkgs.py", line 221, in identify_packages
    manager.search_for_files(files)
  File "/home/vicky/.local/lib/python2.7/site-packages/reprozip/tracer/linux_pkgs.py", line 140, in search_for_files
    package = self._create_package(pkgname)
  File "/home/vicky/.local/lib/python2.7/site-packages/reprozip/tracer/linux_pkgs.py", line 169, in _create_package
    p.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
ValueError: Mixing iteration and read methods would lose data
````

This might bear looking into. Cheers!

**Comment by remram44** [comment]
I think I know what this is, e6f560e7 should fix this. I thought it was a good idea 😅
