### ISSUE TITLE
Elasticsearch doesn't work in chroots: requires / to be a mountpoint

### ISSUE THREAD

**Issue by remram44** [VIDA-NYU/reprozip#235]
For somewhat arbitrary reason, Elasticsearch's file locking code does a bunch of sanity checks and will error out if `/` is not a mountpoint. This is not the case when running in a chroot.

While the correct fix is definitely for Elasticsearch to accept to run in chroots (elastic/elasticsearch#12018), there might be some possible workarounds in reprounzip-vagrant.

* It is possible to make `/` a mountpoint by bind-mounting it from somewhere else and chrooting in the mount
* Also, might be good to create a fake fstab? With at least an entry for `/`? Docker mounts a few key files into the container (such as hosts, resolv.conf), we might want to do that

**Comment by idreamerhx** [comment]
still not work in chroot.

Caused by: java.io.IOException: Mount point not found
        at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91) ~[?:?]
        at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65) ~[?:?]
        at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44) ~[?:?]
        at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51) ~[?:?]
        at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368) ~[?:?]
        at java.nio.file.Files.getFileStore(Files.java:1461) ~[?:1.8.0_192]
        at org.elasticsearch.env.Environment.getFileStore(Environment.java:324) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.env.NodeEnvironment$NodePath.<init>(NodeEnvironment.java:108) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:209) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:267) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.4.jar:6.5.4]

**Comment by remram44** [comment]
I don't think you can mount a directory over itself. The doc you linked is for Docker, not chroot.

I could make a fix for this in reprounzip-vagrant, but I don't feel so good adding something weird only for one application... Might be worth doing since Elasticsearch is so common, though...
